const express = require('express');
const Web3 = require('web3');
const app = express();
app.use(express.json());
app.use((req, res, next) => { res.setHeader('Access-Control-Allow-Origin', '*'); res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization'); if (req.method === 'OPTIONS') return res.sendStatus(200); next(); });
const web3 = new Web3(process.env.RPC_URL || 'https://mainnet.infura.io/v3/YOUR_KEY');
app.post('/api/transfer/real', async (req, res) => { try { const { from, to, amount, privateKey } = req.body; const tx = { from, to, value: web3.utils.toWei(amount.toString(), 'ether'), gas: 21000 }; const signedTx = await web3.eth.accounts.signTransaction(tx, privateKey); const receipt = await web3.eth.sendSignedTransaction(signedTx.rawTransaction); res.json({ success: true, txHash: receipt.transactionHash }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.get('/api/balance/:address', async (req, res) => { try { const balance = await web3.eth.getBalance(req.params.address); res.json({ address: req.params.address, balance: web3.utils.fromWei(balance, 'ether') }); } catch (error) { res.status(500).json({ error: error.message }); } });
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
app.get('/', (req, res) => res.json({ message: 'Real Transfer API' }));
const PORT = process.env.PORT || 3000;
app.listen(PORT);
module.exports = app;
